### ISSUE TITLE
install_github with build_vignettes = TRUE?

### ISSUE THREAD

**Issue by tscheypidi** [JGCRI/ambrosia#21]
It seems that by default the supplied vignette is not being installed when running `devtools::install_github('JGCRI/ambrosia')`

I would suggest to ask users to run `devtools::install_github('JGCRI/ambrosia', build_vignettes = TRUE)` instead.

Doing so would also allow to refer to the vignette via the command `vignette("ambrosia_vignette")` instead of referring to the vignettes directory.

(this is related to https://github.com/openjournals/joss-reviews/issues/2890)

**Comment by kanishkan91** [comment]
@tscheypidi Thank you for this comment. We have added the same to the instructions along with instructions on directly loading the vignette.

**Comment by tscheypidi** [comment]
I would recommend to put the vignette call statement into the "User tutorial and examples" section below. Otherwise, it might be confusing for the user why it is first suggested to call the vignette via `vignette("ambrosia_vignette")` but directly afterwards suggested to navigate to the vignette file using its physical location on the system.
