### ISSUE TITLE
parameters unclear

### ISSUE THREAD

**Issue by tscheypidi** [JGCRI/ambrosia#22]
As the parameters seem to have a central role in the whole process a bit more explanation and a better visibility of these explanations throughout the documentation would be useful. Some examples

- `A_s` is described as "Scaling parameter for staples (constant)", but it is unclear to me how it works. What exactly is scaled here and which range of scaling factors makes sense? How can these parameters be estimated?
- All parameters lack unit information
- In the vignette the parameter names are introduced and used, but they are not explained. Also a link to a page explaining these parameters is not available.
- vec2param (and probably other documentation pages) are mentioning the parameter names, but not explaining what it is (sidnode: in case of 8 parameters it looks like the documentation is only explaining what the first 7 are, but not what the 8th parameter is).

Please check again the documentation with a focus on the parameters and make sure that the correspoding parameters are either explained on the page or the parameter description is linked along with the use of these parameter names

https://github.com/openjournals/joss-reviews/issues/2890

**Comment by kanishkan91** [comment]
@tscheypidi Thanks much for this comment.  We will work on making the explanations more clear. The problem is that the equations are documented in the paper, the estimation framework is documented in a separate function and parameter bounds are documented separately in another function. We will try to bring this all together meaningfully and get back to you shortly. If you have any other suggestions related to this, do let us know.

**Comment by tscheypidi** [comment]
based on the vignette my understanding is that the parameters need to be provided in the predefined structure currently created by `vec2param`. Currently, already needs to know which parameters (in which ranges) in which order need to be provided to that function as `x`.

What you could do for better usability but also documentation would be also to allow the provision of all parameters as single arguments. This could be either done in `vec2param` itself as alternative input method, or in another function which also returns a parameter object. It could look something like this:

```
input2param <- function(A_s=1.28, A_n=1.14, xi_ss=-0.19, xi_cross=0.21, 
                                     xi_nn=-0.33, nul_n=0.5, lambda_s=0.1, 
                                     k_s=16, Pm=5.06,
                                     psscl=100, pnscl=20)
```
or 

```
vec2param <- function(x=NULL, A_s=1.28, A_n=1.14, xi_ss=-0.19, xi_cross=0.21, 
                                     xi_nn=-0.33, nul_n=0.5, lambda_s=0.1, 
                                     k_s=16, Pm=5.06,
                                     psscl=100, pnscl=20)
```
In the latter the single element parameter entries would be ignored if provided via `x`.

Putting each argument explicitly in the function call would have the following advantages:

- The documentation of that function would provide you with a structured setting to properly document each parameter with default values (which could be set as default as shown in the example), meaning, unit and ranges
- You could refer in all other functions to the documentation of this function for explanation of the parameters
- Novice users could create a default parameter object easily via calling `input2param()` or `vec2param()`
